[package]
name = "uuid"
version = "0.1.0"
workspace = "../../"
publish = false

[dependencies]
rocket = { path = "../../core/lib" }
lazy_static = "1.0"
uuid = "0.7"

[dependencies.rocket_contrib]
default-features = false
path = "../../contrib/lib"
features = ["uuid"]
